### ISSUE TITLE
[QUESTION] Mac Catalyst Support

### ISSUE THREAD

**Issue by willm132** [toastersocks/MultiPicker#2]
Does this support Mac Catalyst?

**Comment by toastersocks** [comment]
@willm132 I haven't explicitly tested it with macCatalyst, but I don't see why it wouldn't work. Very likely to work in designed for iPad mode, but I feel less sure about the mode that tries to bridge closer to macOS design. I'll test it when I get some time.

**Comment by aehlke** [comment]
Native non-Catalyst SwiftUI for macOS is also ideal

**Comment by toastersocks** [comment]
> Native non-Catalyst SwiftUI for macOS is also ideal

@aehlke if you're looking for this functionality on macOS, you can use the native SwiftUI.Picker which supports optional and multiple selections on that platform. However on iOS, this is not supported. MultiPicker exists to fill this gap on iOS.

**Comment by aehlke** [comment]
Thanks but I don't believe it can be styled with checkmarks like yours, or otherwise styled as selection components, which don't require holding a modifier key while clicking to multi-select

**Comment by toastersocks** [comment]
@aehlke Oh, I see what you mean. Yes, you're right, it's not quite the same. It would be useful. Lots of different design options (radio buttons, checkboxes, highlighting the whole cell, menu style) for mac. Menu style is something I'd personally be interested in for both iOS and macOS.
Is there any particular style of multi-picker that you're especially keen on having for macOS?

**Comment by aehlke** [comment]
I'll think more about it and get back to you with more specific use case. I suppose checkbox style is most native feeling.

**Comment by toastersocks** [comment]
@aehlke Ok, sounds good. I imagine we'd want multiple styles supported, but I feel like things usually turn out better when I base my work/designs around real-world use-cases. I'll go ahead and close this for now, but feel free to open another issue if you come up with a concrete use-case of a multi-picker style you'd want to use 🙂

**Comment by toastersocks** [comment]
> Does this support Mac Catalyst?

@willm132 I just tested it, and it looks like it works just fine in both macCatalyst modes 👍

**Comment by aehlke** [comment]
I realized I can do a lot with Form too already. But it's another scroll view.

**Comment by toastersocks** [comment]
@aehlke Oh, can you elaborate? Maybe it's an approach I can take on mac.

**Comment by aehlke** [comment]
https://www.fline.dev/multi-selector-in-swiftui/ has some examples. don't have macos screens on hand to compare.
