### ISSUE TITLE
Preview error during archive process

### ISSUE THREAD

**Issue by ThomasBernard03** [toastersocks/MultiPicker#6]
Hello, I have several errors when I try to archive my project using your package. 
<img width="368" alt="image" src="https://github.com/user-attachments/assets/13af678d-b9da-4f9b-8274-3359578d1b2b">
All errors are related to previews: 
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/94e643be-123d-4c66-832d-c324bcf7aedc">
This seems to be the solution:
https://stackoverflow.com/questions/63078880/why-does-archive-fail-if-there-is-code-for-swiftui-previews-in-the-preview-conte

**Comment by toastersocks** [comment]
@ThomasBernard03 thanks for reporting this. I'm out of the country currently, so it'll be a couple weeks before I get to this. Feel free to submit a pull request if you have a fix, otherwise I'll get to this when I return.

**Comment by ThomasBernard03** [comment]
Digging through the code, I saw that all the previews were surrounded by #if DEBUG. In the end, I just wasn't using the latest version of the package. I updated to 1.1 and everything works. Sorry for the inconvenience.

**Comment by toastersocks** [comment]
Ah ok, great! No problem, I'm glad you were able to find a solution🎉
