### ISSUE TITLE
Any special concerns regarding why macOS support is missing?

### ISSUE THREAD

**Issue by ShikiSuen** [toastersocks/MultiPicker#7]
Just my curiosity.

**Comment by toastersocks** [comment]
@ShikiSuen `SwiftUI.Picker` already supports optional and multi selection on macOS. This library was mainly created to fill in this gap in functionality for iOS. I'm open to making it available on macOS, but I couldn't find a design that I liked that I thought fit well with macOS UX and haven't had the time to investigate further. 
I'm open to suggestions and/or PRs 🙂

**Comment by ShikiSuen** [comment]
@toastersocks 

Here are my thoughts if the user interface idiom is macOS or AppKit is used for the app in lieu of UIKit (macCatalyst):

If the picker is placed inside a Form with `.formStyle(.grouped)`, then just make it look exactly like what single picker appears in a grouped form.

Otherwise, a vertically stacked list of checkboxes should make sense.

**Comment by toastersocks** [comment]
@ShikiSuen 
> If the picker is placed inside a Form with `.formStyle(.grouped)`, then just make it look exactly like what single picker appears in a grouped form.

Last I checked, there's no way to query the environment to get the context that a view is appearing in, so having a separate appearance based on whether we're in a Form or not, let alone the style of the Form is SwiftUI internal API not currently available to third-party devs, unfortunately.

> Otherwise, a vertically stacked list of checkboxes should make sense.

I'm curious what is the functionality you're wanting from `MultiPicker` on macOS that's not currently provided by  `SwiftUI.Picker`?

**Comment by ShikiSuen** [comment]
> I'm curious what is the functionality you're wanting from `MultiPicker` on macOS that's not currently provided by `SwiftUI.Picker`?

I'm not sure. As long as it allows multiple choices, it should be fine.

**Comment by toastersocks** [comment]
Ok, I'm closing this for now. Feel free to reopen/open another issue if you encounter a use case on macOS.
